#!/usr/bin/env php
<?php
set_time_limit (0);

$file_path = "/tmp/kiki_source_" . rand(1000,9999);
$temp_file = "/tmp/" . rand(10000,99999) .".tar";
$release_file = "~/kiki_framework_1_".date("Ymd",time()).".tar.gz";


shell_exec("mkdir {$file_path}");
shell_exec("tar cf $temp_file .");
shell_exec("tar xf $temp_file -C $file_path");
shell_exec("rm {$file_path}/.idea -rf");
shell_exec("rm {$file_path}/.git -rf");
shell_exec("rm {$file_path}/.env -f");
shell_exec("rm {$file_path}/store/cache/* -rf");
shell_exec("rm {$file_path}/models/.no-data -f");

shell_exec("rm {$file_path}/models/dtest* -f");
shell_exec("rm {$file_path}/controllers/dtest* -f");

shell_exec("rm {$file_path}/source_package -f");
shell_exec("touch {$file_path}/.new");

shell_exec("tar zcf {$release_file} -C {$file_path} .");

shell_exec("rm {$file_path} -rf");

echo "Package is finished , filename: $release_file \n";




